import Image from 'next/image';
import Link from 'next/link';
import { House, Trees, Leaf, Clapperboard, MapPin } from 'lucide-react';
import { content } from '@/content/locales';
import { photos, rooms, site, type Locale } from '@/config/site';
import { Address, Gallery, InquiryForm } from './interactive';

export function Photo({index,className='',priority=false}:{index:number;className?:string;priority?:boolean}) {const p=photos[index];return <div className={`photo ${className}`}><Image src={p.src} alt={p.ko} width={p.width} height={p.height} priority={priority} sizes="(max-width: 760px) 100vw, 70vw"/></div>;}
export function LocalPhoto({index,locale,className='',priority=false}:{index:number;locale:Locale;className?:string;priority?:boolean}){const p=photos[index];return <div className={`photo ${className}`}><Image src={p.src} alt={p[locale]} width={p.width} height={p.height} priority={priority} sizes="(max-width: 760px) 100vw, 70vw"/></div>;}
export function CTA({locale}:{locale:Locale}){const c=content[locale];return <section className="cta container"><p className="eyebrow">BOOK YOUR STAY</p><h2>{c.finalTitle}</h2><p>{c.finalText}</p><div className="buttons"><Link className="button" href={`/${locale}/contact`}>{c.book}</Link><Link className="text-link" href={`/${locale}/contact#inquiry`}>{c.inquire}</Link></div></section>;}
export function Footer({locale}:{locale:Locale}){const c=content[locale];return <><footer><div className="container"><div className="footer-top"><Link className="logo" href={`/${locale}`}><strong>{locale==='ko'?'강 산 재':'KANGSANJAE'}</strong><span>PRIVATE HANOK RETREAT</span></Link><nav>{['about','stay','experiences','filming','gallery','explore','guide','contact'].map((p)=><Link key={p} href={`/${locale}/${p}`}>{c.titles[p as keyof typeof c.titles]}</Link>)}</nav></div><div className="footer-details"><p>{locale==='ko'?site.address:site.addressEn}</p><p>{c.contactPending} · {c.business}</p><div>{site.links.phone&&<a href={`tel:${site.links.phone}`}>{site.links.phone}</a>}{site.links.email&&<a href={`mailto:${site.links.email}`}>{site.links.email}</a>}{site.links.instagram?<a href={site.links.instagram}>Instagram</a>:<span>Instagram · {c.linkPending}</span>}</div></div><div className="footer-bottom"><small>© 2026 KANGSANJAE. {c.copyright}</small><div><Link href={`/${locale}/privacy`}>{c.titles.privacy}</Link><Link href={`/${locale}/terms`}>{c.titles.terms}</Link></div></div></div></footer><Link className="mobile-book button" href={`/${locale}/contact`}>{c.book}</Link></>;}
function SectionHeading({label,title,text,link,linkText}:{label:string;title:string;text?:string;link?:string;linkText?:string}){return <div className="section-heading"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div><div className="section-meta">{text&&<p>{text}</p>}{link&&<Link className="text-link" href={link}>{linkText}</Link>}</div></div>;}
export function RoomCards({locale}:{locale:Locale}){const c=content[locale];return <div className="room-grid">{rooms.map(r=><article key={r.slug} className="room-card"><Link href={`/${locale}/stay/${r.slug}`}><LocalPhoto index={r.photo} locale={locale}/></Link><div className="card-body"><p className="caption">{c.previewRoom}</p><h3>{r.name[locale]}</h3><p>{r.description[locale]}</p><p className="small-text">{c.roomFacts[0]}: {c.pending}</p><div className="card-links"><Link className="text-link" href={`/${locale}/stay/${r.slug}`}>{c.details}</Link><Link className="text-link" href={`/${locale}/contact`}>{c.book}</Link></div></div></article>)}</div>;}
const experiencePhotos=[5,null,3,null,null,1,null];
export function ExperienceCards({locale,full=false}:{locale:Locale;full?:boolean}){const c=content[locale];return <div className="experience-grid">{c.experiences.slice(0,full?7:3).map((name,i)=><article className="experience-card" key={name} id={`experience-${i}`}>{experiencePhotos[i]!==null?<LocalPhoto index={experiencePhotos[i]!} locale={locale}/>:<div className="image-placeholder"><Leaf size={38} strokeWidth={1}/><span>{c.photoPending}</span></div>}<div className="card-body"><h3>{name}</h3><p>{c.expTexts[i]}</p>{full?<dl className="mini-facts">{c.expFields.map(f=><div key={f}><dt>{f}</dt><dd>{c.pending}</dd></div>)}</dl>:<Link className="text-link" href={`/${locale}/experiences#experience-${i}`}>{c.details}</Link>}</div></article>)}</div>;}
export function Home({locale}:{locale:Locale}){const c=content[locale];const icons=[House,Trees,Leaf,Clapperboard];return <><section className="hero"><LocalPhoto index={2} locale={locale} priority/><div className="hero-shade"/><div className="container hero-content"><p className="eyebrow">HONGCHEON · PRIVATE HANOK RETREAT</p><h1>{c.hero}</h1><p className="hero-sub">{c.heroSub}</p><div className="buttons"><Link className="button glass" href={`/${locale}/stay`}>{c.stay}</Link><Link className="button" href={`/${locale}/contact`}>{c.book}</Link></div></div><span className="hero-mark">KANGSANJAE · 01</span></section><section className="features container">{c.features.map((f,i)=>{const Icon=icons[i];return <Link key={f} href={`/${locale}/${['stay','about','experiences','filming'][i]}`}><Icon size={37} strokeWidth={1}/><h3>{f}</h3><p>{c.featureTexts[i]}</p></Link>;})}</section><section className="intro container"><div><p className="eyebrow">KANGSANJAE</p><h2>{c.introTitle}</h2><p>{c.intro}</p><Link className="text-link" href={`/${locale}/about`}>{c.aboutMore}</Link></div><LocalPhoto index={5} locale={locale}/><LocalPhoto index={1} locale={locale} className="intro-second"/></section><section className="section muted"><div className="container"><SectionHeading label="STAY" title={c.titles.stay} text={c.stayIntro} link={`/${locale}/stay`} linkText={c.allStay}/><RoomCards locale={locale}/></div></section><section className="section container"><SectionHeading label="WELLNESS & EXPERIENCES" title={c.expTitle} text={c.expIntro} link={`/${locale}/experiences`} linkText={c.allExperiences}/><ExperienceCards locale={locale}/></section><section className="film-banner"><LocalPhoto index={3} locale={locale}/><div className="container"><p className="eyebrow">A SCENE TO REMEMBER</p><h2>{c.filmTitle}</h2><p>{c.filmText}</p><Link className="button glass" href={`/${locale}/filming`}>{c.story}</Link></div></section><section className="section container seasons"><SectionHeading label="SEASONS AT KANGSANJAE" title={c.seasonTitle} text={c.seasonText} link={`/${locale}/gallery`} linkText={c.gallery}/><div className="season-grid">{c.seasons.map((s,i)=><div className="season" key={s}>{i===0?<LocalPhoto index={1} locale={locale}/>:<div className="season-placeholder"><span>0{i+1}</span><Leaf size={30} strokeWidth={1}/></div>}<div><h3>{s}</h3><p>{i===0?c.featureTexts[1]:c.photoPending}</p></div></div>)}</div></section><section className="reviews container"><p className="eyebrow">GUEST STORIES</p><h2>{c.reviewsTitle}</h2><div className="empty"><p>{c.reviewsEmpty}</p><small>{c.reviewsText}</small></div></section><section className="location-split"><div className="location-image"><LocalPhoto index={5} locale={locale}/><div><p className="eyebrow">LOCATION</p><h2>{c.locationTitle}</h2><Link className="button glass" href={`/${locale}/explore`}>{c.directions}</Link></div></div><CTA locale={locale}/></section></>;}
export function PageHero({locale,title,label,text,photo=0}:{locale:Locale;title:string;label:string;text?:string;photo?:number}){return <><div className="page-heading container"><p className="eyebrow">{label}</p><h1>{title}</h1>{text&&<p>{text}</p>}</div><LocalPhoto index={photo} locale={locale} className="page-panorama"/></>;}
export function ContentPage({locale,page}:{locale:Locale;page:string}){const c=content[locale];const title=c.titles[page as keyof typeof c.titles];
  if(page==='stay')return <><PageHero locale={locale} title={title} label="STAY" text={c.stayIntro} photo={4}/><section className="section container"><p className="notice">{c.roomNote}</p><RoomCards locale={locale}/><div className="facts"><h2>{c.titles.guide}</h2>{c.roomFacts.map(f=><div key={f}><span>{f}</span><span>{c.pending}</span></div>)}</div></section><CTA locale={locale}/></>;
  if(page==='experiences')return <><PageHero locale={locale} title={title} label="WELLNESS & EXPERIENCES" text={c.expIntro} photo={5}/><section className="section container"><ExperienceCards locale={locale} full/></section><CTA locale={locale}/></>;
  if(page==='gallery')return <><div className="page-heading container"><p className="eyebrow">MOMENTS AT KANGSANJAE</p><h1>{title}</h1></div><section className="container gallery-section"><Gallery locale={locale}/></section><CTA locale={locale}/></>;
  if(page==='about')return <><PageHero locale={locale} title={title} label="OUR STORY" text={c.intro} photo={1}/><section className="section container about-layout"><div><p className="eyebrow">KANGSANJAE</p><h2>{c.introTitle}</h2>{c.aboutSections.map((s,i)=><div className="text-block" key={s}><h3>{s}</h3><p>{c.aboutTexts[i]}</p></div>)}</div><div><LocalPhoto index={5} locale={locale}/><LocalPhoto index={4} locale={locale}/><p className="caption">{c.roomNote}</p></div></section><section className="film-banner"><LocalPhoto index={2} locale={locale}/><div className="container"><h2>{c.filmTitle}</h2><p>{c.filmText}</p><Link className="button glass" href={`/${locale}/filming`}>{c.story}</Link></div></section><CTA locale={locale}/></>;
  if(page==='filming')return <><PageHero locale={locale} title={title} label="FILMING & VENUE" text={c.filmIntro} photo={2}/><section className="section container"><div className="venue-types">{c.filmTypes.map((t,i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3></div>)}</div><div className="two-columns"><LocalPhoto index={0} locale={locale}/><div>{c.filmInfo.map((t,i)=><div className="text-block" key={t}><h2>{t}</h2><p>{c.filmInfoTexts[i]}</p></div>)}</div></div><InquiryForm locale={locale} filming/></section></>;
  if(page==='explore')return <><PageHero locale={locale} title={title} label="YOUR JOURNEY" text={c.exploreIntro} photo={5}/><section className="section container"><div className="two-columns"><div><MapPin size={30} strokeWidth={1}/><h2>{c.locationTitle}</h2><Address locale={locale}/></div><div className="map-placeholder"><MapPin size={44} strokeWidth={1}/><p>{c.mapPlaceholder}</p><a className="text-link" href={site.mapUrl} target="_blank" rel="noopener noreferrer">{c.directions}</a></div></div><div className="guide-grid">{c.transportTitles.map((t,i)=><article className="text-block" key={t}><p className="eyebrow">0{i+1}</p><h2>{t}</h2><p>{c.transportTexts[i]}</p></article>)}</div></section><CTA locale={locale}/></>;
  if(page==='guide')return <><PageHero locale={locale} title={title} label="BEFORE YOUR STAY" text={c.guideIntro} photo={4}/><section className="section narrow"><div className="accordion">{c.guideTitles.map(t=><details key={t}><summary>{t}</summary><p>{c.guideAnswer}</p></details>)}</div><h2 className="spaced-heading">{c.cultureHeading}</h2>{c.cultureTitles.map((t,i)=><div className="text-block" key={t}><h3>{t}</h3><p>{c.cultureTexts[i]}</p></div>)}<h2 className="spaced-heading">{c.faqTitle}</h2>{c.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><CTA locale={locale}/></>;
  if(page==='contact')return <><div className="page-heading container"><p className="eyebrow">BOOK YOUR STAY</p><h1>{title}</h1><p>{c.contactIntro}</p></div><section className="container contact-layout"><div className="booking-panel"><h2>{c.book}</h2>{['naver','airbnb','phone','kakao','email','instagram'].map((key,i)=>{const url=site.links[key];return url?<a className="channel" key={key} href={key==='phone'?`tel:${url}`:key==='email'?`mailto:${url}`:url}>{c.bookingChannels[i]}</a>:<div className="channel disabled" aria-disabled="true" key={key}><span>{c.bookingChannels[i]}</span><small>{key==='phone'||key==='email'?c.contactPending:c.linkPending}</small></div>;})}<Link className="text-link" href={`/${locale}/filming#inquiry`}>{c.filmFormTitle}</Link><div className="text-block"><h3>{c.titles.explore}</h3><Address locale={locale}/></div></div><InquiryForm locale={locale}/></section></>;
  return <div className="section narrow"><p className="eyebrow">KANGSANJAE</p><h1>{title}</h1><p>{c.policyText}</p><p className="notice">{c.pending}</p><Link className="button" href={`/${locale}/contact`}>{c.inquire}</Link></div>;
}
export function RoomDetail({locale,slug}:{locale:Locale;slug:string}){const c=content[locale];const room=rooms.find(r=>r.slug===slug)!;return <><PageHero locale={locale} title={room.name[locale]} label="HANOK SPACE PREVIEW" text={room.description[locale]} photo={room.photo}/><section className="section container"><p className="notice">{c.previewRoom}. {c.roomNote}</p><div className="two-columns"><div><h2>{c.stay}</h2><p>{room.description[locale]}</p><div className="facts">{c.roomFacts.map(f=><div key={f}><span>{f}</span><span>{c.pending}</span></div>)}</div><h3>{c.titles.guide}</h3><p>{c.guideAnswer}</p><Link className="text-link" href={`/${locale}/guide`}>{c.details}</Link></div><div><LocalPhoto index={0} locale={locale}/><LocalPhoto index={2} locale={locale}/></div></div><div className="buttons"><Link className="button" href={`/${locale}/contact`}>{c.book}</Link><Link className="text-link" href={`/${locale}/gallery`}>{c.gallery}</Link></div><h2 className="spaced-heading">{c.otherRooms}</h2><div className="room-grid">{rooms.filter(r=>r.slug!==slug).map(r=><article className="room-card" key={r.slug}><LocalPhoto index={r.photo} locale={locale}/><div className="card-body"><h3>{r.name[locale]}</h3><Link className="text-link" href={`/${locale}/stay/${r.slug}`}>{c.details}</Link></div></article>)}</div></section><CTA locale={locale}/></>;}
